site_name: FluidPatcher
repo_url: https://github.com/GeekFunkLabs/fluidpatcher
nav:
- Home: README.md
- Setup:
  - Installation: install.md
  - Configuration: config.md
- Concepts:
  - Overview: concepts/overview.md
  - Soundfonts: concepts/soundfonts.md
  - Banks & Patches: concepts/banks.md
  - MIDI Event Processing: concepts/midi.md
  - Players & Sequencers: concepts/players.md
  - Effects (LADSPA): concepts/ladspa.md
- Bank Tutorials:
  - Basics: tutorial/lesson01_basic.md
  - Messages: tutorial/lesson02_messages.md
  - Router Rules: tutorial/lesson03_rules.md
  - Players & Sequencers: tutorial/lesson04_players.md
  - Effects (LADSPA): tutorial/lesson05_effects.md
  - Cookbook: tutorial/cookbook.md
- API Reference:
  - Patcher: api/patcher.md
  - Banks: api/bankfiles.md
  - Config/Exceptions: api/misc.md
theme:
  name: readthedocs
  favicon: img/gfl_logo.ico
plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_section_style: list
            members_order: source
            show_root_heading: true
            show_signature_annotations: true
